### ISSUE TITLE
Cheee. los sanrafaelinos.. pa cuando un asado?

### ISSUE THREAD

**Issue by nickzf57** [CodeSystem2022/WorkBots_Tercer_Semestre#1]

**Comment by ivi2002** [comment]
que lindo una juntada!!! digan cuando

**Comment by Titim19** [comment]
Cuando Digan... vos encárgate Nico

**Comment by Titim19** [comment]
Chicos hay que tener preparado el  dialogo de ingles... y el proyecto del profe ariel
que les parece si mañana en horario de 16hs nos reunimos y charlamos

**Comment by Leonela2604** [comment]
Hola, recién ingreso me pinta un asado jaja
