### ISSUE TITLE
11.2 Diferentes Querys en MySQL - Video 3

### ISSUE THREAD

**Issue by FacundoGiuliano** [CodeSystem2022/WorkBots_Tercer_Semestre#15]

**Comment by Titim19** [comment]
A lo ya realizado en  el video 2 de la clase 11 sobre MYSQL, se siguió creando querty y los comandos para insertar (insertar into), eliminar (delete from) (alet table) para incrementar (autoincremento).

**Comment by Titim19** [comment]
tarea asiganda terminada
