### ISSUE TITLE
11.3 Sincronizamos con Maven y agregamos la dependencia - Video 4

### ISSUE THREAD

**Issue by FacundoGiuliano** [CodeSystem2022/WorkBots_Tercer_Semestre#16]

**Comment by Leonela2604** [comment]
En el video 4 comenzamos un nuevo proyecto llamado SistemaEstudiantes (leccion12), donde vamos a utilizar IntelliJ con Java y Maven. Utilizaremos las siguientes dependencias en el archivo pom.xml:

<groupId>UTN</groupId>
<artifactId>estudiante</artifactId>
<version>1.0-SNAPSHOT</version>

 <properties>
        <maven.compiler.source>15</maven.compiler.source>
        <maven.compiler.target>15</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

Esto nos permitirá gestionar el proyecto de manera eficiente y asegurar la correcta administración de las dependencias y versiones en el desarrollo del proyecto.
